name: nightly

# on:
#  push:
#   branches:
#    - master

jobs:
  publish-nightly:
    runs-on: ubuntu-latest

    container:
      image: arduino/arduino-cli:builder-1
      volumes:
        # cache go dependencies across pipeline's steps
        - ${{github.workspace}}/go:/go


    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: build
        env:
          PACKAGE_NAME_PREFIX: ${{ github.workflow }}
        run: goreleaser --snapshot

      - name: upload
        uses: docker://plugins/s3
        env:
          PLUGIN_SOURCE: 'dist/*'
          PLUGIN_TARGET: '/arduino-cli/nightly'
          PLUGIN_STRIP_PREFIX: 'dist/'
          PLUGIN_BUCKET: ${{ secrets.DOWNLOADS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
