name: release

on:
  push:
    tags:
      - '[0-9].[0-9].[0-9]*'

jobs:

  create-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Identify Prerelease
        id: prerelease 
        run: |
          wget -q https://github.com/fsaintjacques/semver-tool/archive/3.0.0.zip
          unzip -p 3.0.0.zip semver-tool-3.0.0/src/semver > semver
          rm -f 3.0.0.zip
          if [[ $(./semver get prerel ${GITHUB_REF/refs\/tags\//}) ]]; then 
            echo "::set-output name=IS_PRE::true" 
          else
            echo "::set-output name=IS_PRE::false"
          fi
   
      - name: Create Github Release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.hangelog.outputs.BODY }}
          draft: false
          prerelease: ${{ steps.prerelease.outputs.IS_PRE }}

  
