name: test

# on:
#   push:
#     branches:
#       - master
#   pull_request:

jobs:
  test-matrix:

    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Disable EOL conversions
        run: git config --global core.autocrlf false

      - name: Checkout
        uses: actions/checkout@master

      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.14'

      - name: Install Go deps
        # Since 10/23/2019 pwsh is the default shell
        # on Windows, but pwsh fails to install protoc-gen-go so
        # we force bash as default shell for all OSes in this task
        run: |
          go get github.com/golangci/govet
          go get golang.org/x/lint/golint
          go get github.com/golang/protobuf/protoc-gen-go
        shell: bash

      - name: Install Taskfile
        uses: Arduino/actions/setup-taskfile@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check the code is good
        run: task check

      - name: Install protoc compiler
        uses: arduino/setup-protoc@v1.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check protocol buffers compile correctly
        run: task protoc

      - name: Build the CLI
        run: task build

      - name: Run unit tests
        run: task test-unit

      - name: Run unit tests on the legacy package
        # Run legacy tests on one platform only
        if: matrix.operating-system == 'ubuntu-latest'
        run: task test-legacy

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Run integration tests
        run: |
          pip install -r test/requirements.txt
          task test-integration

      - name: Send unit tests coverage to Codecov
        # Since secrets aren't available on forks, we only
        # upload coverage on `push`. This might change if
        # Codecov whitelists GitHub, lifting the need
        # for a token.
        if: >
          matrix.operating-system == 'ubuntu-latest' &&
          github.event_name == 'push'
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage_unit.txt
          flags: unit

      - name: Send legacy tests coverage to Codecov
        # Since secrets aren't available on forks, we only
        # upload coverage on `push`. This might change if
        # Codecov whitelists GitHub, lifting the need
        # for a token.
        if: >
          matrix.operating-system == 'ubuntu-latest' &&
          github.event_name == 'push'
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage_legacy.txt
          flags: unit

      - name: Send integration tests coverage to Codecov
        # Since secrets aren't available on forks, we only
        # upload coverage on `push`. This might change if
        # Codecov whitelists GitHub, lifting the need
        # for a token.
        if: >
          matrix.operating-system == 'ubuntu-latest' &&
          github.event_name == 'push'
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage_integ.txt
          flags: integ
